s/CC=cc $(ABI_FLAG)/CC=gcc $(ABI_FLAG)/g
s/AS=as $(ABI_FLAG)/AS=gcc -c -x assembler-with-cpp $(ABI_FLAG)/g
s|CFLAGS= -O -I$(srcdir)/include -DATOMIC_UNCOLLECTABLE -DNO_SIGNALS -DNO_EXECUTE_PERMISSION -DSILENT -DALL_INTERIOR_POINTERS|CFLAGS= -O -I$(srcdir)/include -DATOMIC_UNCOLLECTABLE -DNO_SIGNALS -DNO_EXECUTE_PERMISSION -DSILENT -DALL_INTERIOR_POINTERS -DLARGE_CONFIG -DUSE_MMAP -DDONT_ADD_BYTE_AT_END|g
