#!/bin/sh
rm -rf include/gc.h
rm -rf include/gc_config_macros.h.h
rm -rf include/Tmk.h
rm -rf include/libgc.a
rm -rf include/libstalin.a
rm -rf include/libTmk.a
rm -rf include/stalin
rm -rf stalin.c
rm -rf stalin
cd benchmarks
./make-clean
