#!/bin/sh

if ! echo "$*" | grep -qE '(^|[[:space:]])-On([[:space:]]|$$)'
then
  echo "stalin: For now, you must specify -On because safe fixnum arithmetic is"
  echo "stalin: not (yet) implemented."
  exit 1
fi

exec /usr/lib/stalin/stalin -copt -I -copt /usr/include/gc -I /usr/lib/stalin $@
